---
version: "3.9"
services:
  db:
    image: postgres:12-alpine
    volumes:
      - ./dev/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
      - ./dev/db/script:/script:ro
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  backend:
    image: python:3.8.5
    working_dir: /app
    command: ["./test.sh"]
    volumes:
      - ./dev/backend:/app:delegated
      - ./src/AkvoDjangoFormGateway:/app/AkvoDjangoFormGateway:delegated
    environment:
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
      - DB_SCHEMA=demo
      - DB_USER=akvo
      - DB_PASSWORD=password
      - DB_HOST=db
    depends_on:
      - db
    ports:
      - 8000:8000
volumes:
  pg-data:
